version: '3.0'
services:
    gnujdb:
        build: .
        restart: unless-stopped
        volumes:
            - /mnt/vdb1/d33tah/gnujdb/media:/media
            - /mnt/vdb1/d33tah/gnujdb/db.sqlite3:/db.sqlite3
        network_mode: bridge
        labels:
            traefik.http.routers.g-https.entrypoints: websecure
            traefik.http.routers.g-https.rule: Host(`g.hs-ldz.pl`)
            traefik.http.routers.g-https.tls.certresolver: myresolver
            traefik.http.routers.g.entrypoints: web
            traefik.http.routers.g.rule: Host(`g.hs-ldz.pl`)
