networks:
  default:
    name: traefik
    external: true

services:
    gnujdb:
        build: .
        restart: unless-stopped
        volumes:
            - /mnt/vdb1/d33tah/gnujdb/media:/media
            - type: bind
              source: ./db.sqlite3
              target: /db.sqlite3
        labels:
            traefik.http.routers.g-https.entrypoints: websecure
            traefik.http.routers.g-https.rule: Host(`g.hs-ldz.pl`)
            traefik.http.routers.g-https.tls.certresolver: myresolver
            traefik.http.routers.g.entrypoints: web
            traefik.http.routers.g.rule: Host(`g.hs-ldz.pl`)
