# Generated by Django 3.0 on 2020-09-21 12:38

from django.db import migrations, models
import gnujdb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gnuj',
            fields=[
                ('id', models.CharField(default=gnujdb.models.gen_key, max_length=10, primary_key=True, serialize=False)),
                ('tytul', models.TextField()),
                ('wartosc', models.TextField()),
                ('wlasnosc', models.TextField()),
                ('dodatkowe_info', models.TextField(blank=True)),
            ],
        ),
    ]
