# Generated by Django 3.0 on 2020-09-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnujdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnuj',
            name='elo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gnuj',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='gnuj',
            name='tytul',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gnuj',
            name='wartosc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gnuj',
            name='wlasnosc',
            field=models.TextField(blank=True),
        ),
    ]
