# Generated by Django 4.2.8 on 2023-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gnujdb",
            "0002_gnuj_last_updated_alter_gnuj_image_alter_gnuj_tytul_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gnuj",
            name="miejsce",
            field=models.TextField(blank=True),
        ),
    ]
