# Generated by Django 4.2.13 on 2024-05-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnujdb', '0004_auto_20240507_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnuj',
            name='fts_tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gnuj',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gnuj',
            name='pokoj',
            field=models.CharField(choices=[('Mainroom', 'Mainroom'), ('HARDRoom', 'HARDRoom'), ('LAZIENKA', 'LAZIENKA'), ('Narnia', 'Narnia'), ('Korytaz', 'Korytaz'), ('403', '403')], default='Mainroom', max_length=255),
        ),
    ]
